name: Build APK with local Maven lib

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      # Publish your library to Maven Local
      - name: Publish spotdl-android to Maven Local
        run: ./gradlew :spotdl-android:publishToMavenLocal

      # Copy published Maven artifacts to app/libs/maven-repo
      - name: Copy Maven Local to app/libs/maven-repo
        run: |
          mkdir -p app/libs/maven-repo
          cp -r ~/.m2/repository/com/github/groingo/spotdl_android app/libs/maven-repo/com/github/groingo/spotdl_android

      # Build your app APK
      - name: Build Release APK
        run: ./gradlew :app:assembleRelease

      # Upload APK artifact for download
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: Spowlo-release-apk
          path: app/build/outputs/apk/release/app-release.apk
